services:
  - type: web
    name: cityfund-app
    env: node
    plan: free
    buildCommand: npm install && npm run build:prod
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RENDER_EXTERNAL_URL
        value: https://cityfund-app.onrender.com 